---

# This GitHub Actions workflow is designed to be triggered when a release is marked as a full release.
# The workflow performs the following tasks:
# 1. Checks if the tag already exists.
# 2. Tags the commit with the release version.
# 3. Builds and publishes a Docker image.
# 4. Creates a GitHub release.

# To make it work for your project, you need to adjust the pom.xml and add configuration file for GitHub release.
# Please find detailed instructions:
# https://github.com/Netcracker/qubership-workflow-hub?tab=readme-ov-file#docker-project-release-workflow

name: Release And Publish Docker Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'
permissions:
  contents: write
  packages: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ github.event.inputs.version }}
          check-tag: true

  docker-build-publish:
    needs: create-tag
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@v1.0.3
    with:
      artifact-id: ${{ github.event.repository.name }}
      ref: v${{ inputs.version }}
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
      component: '[{"name": "maas", "file": "./maas/Dockerfile", "context": "./maas"}]'
      platforms: linux/amd64,linux/arm64

  cleanup-on-dry-run:
    needs: docker-build-publish
    if: ${{ github.event.inputs.dry-run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ github.event.inputs.version }}
          delete-tag: true

  github-release:
    needs: docker-build-publish
    if: ${{ github.event.inputs.dry-run == 'false' }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v1.0.3
    with:
      version: ${{ github.event.inputs.version }}
      publish: false
